collections:
  stories:
    output: true
  photostories:
    output: true
page_blocks: []
_array_structures:
  page_blocks:
    - label: Vertical Parallax
      icon: image
      value:
        _id: vertical-parallax
        large_image:
        large_image_title:
        large_image_alt_text:
        large_image_caption_text:
    - label: Two Photo Grid
      icon: slideshow
      value:
        _id: two-photo-grid
        grid_top_image:
        grid_top_image_alt_text:
        grid_top_image_caption_text:
        grid_bottom_image:
        grid_bottom_image_alt_text:
        grid_bottom_image_caption_text:
    - label: Horizontal Parallax
      icon: image
      value:
        _id: wide-parallax
        wide_image:
        wide_image_title:
        wide_image_alt_text:
        wide_image_caption_text:
    - label: Hexagon Gallery
      icon: slideshow
      value:
        _id: hexagon-gallery
        hex_one_image:
        hex_one_alt_text:
        hex_two_image:
        hex_two_alt_text:
        hex_three_image:
        hex_three_alt_text:
        hex_four_image:
        hex_four_alt_text:
    - label: Beta Section
      icon: text
      value:
        _id: beta-section
        article_writer:
        article_photographer:
