collections:
  stories:
    output: true

page_blocks: []
_array_structures:
  two-photo-grid:
    - label: Two Photo Grid
      icon: collections
      value:
        _id: two-photo-grid
        caption_top:
        caption_bottom:
        grid_top_image:
        grid_bottom_image:
  full-screen-parallax:
    - label: Full Screen Parallax
      icon: format_quote
      value:
        _id: full-screen-parallax
        image:
        image_title:
        caption_large:
  hexagon-gallery:
    - label: Hexagon Gallery
      icon: collections
      value:
        _id: hexgallery
        image_one:
        image_one_alttxt:
        image_two:
        image_two_alttxt:
        image_three:
        image_three_alttxt:
        image_four:
        image_five:
  vertical-parallax:
    label: Vertical Parallax
    icon: collections
    value:
      _id: vertical-parallax
      image:
      image_title:
      caption_large:
